# -*- coding: utf-8 -*-
"""files_sorting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ra0kC8iZ0tblyxuu0FNBY3CCPPQ9hwnJ
"""

from google.colab import drive
drive.mount('/content/drive')

#from google.colab import files
#uploaded = files.upload()  # This will prompt you to upload files

import os,shutil

path= '/content/drive/My Drive/files_sort/'

os.listdir(path)

file_name=os.listdir(path)

folder_names=['csv files','image files','text files']
for loop in range(0,3):
  if not os.path.exists(path+folder_names[loop]):
    print(f'{folder_names[loop]} folder created')
    os.makedirs(path+folder_names[loop])

for file in file_name:
  if ".xlsx" in file and not os.path.exists(path+'csv files/'+file):
    shutil.move(path+file,path+'csv files/'+file)
  elif ".png" in file and not os.path.exists(path+'image files/'+file):
    shutil.move(path+file,path+'image files/'+file)
  elif ".pdf" in file and not os.path.exists(path+'text files/'+file):
    shutil.move(path+file,path+'text files/'+file)
  else:
    print('no files moved')